### ISSUE TITLE
Breakpoint pulling not working

### ISSUE THREAD

**Issue by SHiLLySiT** [Ismoh/local-lua-debugger-vscode#21]
I found [this thread](https://github.com/tomblind/local-lua-debugger-vscode/pull/67) in the original repo and followed the instructions there on how to pull breakpoints but I'm still not able to get breakpoints added at runtime working.

Here's my `launch.json`:
```json
  "configurations": [
    {
      "type": "lua-local",
      "request": "launch",
      "name": "Debug Love2d",
      "program": {
        "command": "love",
      },
      "args": [
        "_love2d", 
        "LOCAL_LUA_DEBUGGER_VSCODE"
      ],
      "scriptRoots": [
        "_love2d"
      ],
      "pullBreakpointsSupport": true, // enabled support
    }
  ]
```

And my `main.lua`:
```lua
if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
  lldebugger = require("lldebugger")
  lldebugger.start()
end

-- ... etc

function love.draw()
    if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
      lldebugger.pullBreakpoints()
    end
    -- ... etc
end
```

It looks like this repo's readme hasn't been updated to include the new flag, but based on commit 54262e56ab35a00775ffed111780d3a858a8e82f I think this fork has the required changes?

**Comment by sewbacca** [comment]
Yes, pull breakpoints support has been merged. I have tried to reproduce your problem, but it works for me as expected (I am on `0.3.8`). Have you set the breakpoint somewhere it definitely steps over or have you tried turning `stepUnmappedLines` on?

**Comment by SHiLLySiT** [comment]
Ahhh. I just tested again and I think the nuance is that, if I start the debugger without _any_ breakpoints, it won't break on any breakpoints that I add while its running.

However starting the debugger with at least one breakpoint, then adding new breakpoints while its running works correctly :tada:

**Comment by sewbacca** [comment]
This is odd behaviour, as I also started without any breakpoints and then added new ones, which worked fine for me.
Does this issue occur also with the code provided, or do you have a more complicated setup in which this issue occurs?

**Comment by SHiLLySiT** [comment]
Doh, it _is_ working fine 🤦

I do have a bit more complicated setup, so it was possible that when I was testing earlier, I was probably setting the breakpoints in the wrong Lua files (I generate final Lua files from source files).

**Comment by SHiLLySiT** [comment]
Ah actually, I just realized what the nuance was!

As mentioned in my last comment, I have source Lua files that I do some processing on before I generate final Lua files.

If I set breakpoints in the final Lua files, everything works. However, if I set breakpoints in the source Lua files, that's where things start to get wonky. It seems the primary issue is when my processing steps _add_ lines to the final Lua files that don't exist in the source files.

I attached a simple repo project. Specifically in this example, if you start debugging with no breakpoints, then add a breakpoint to `main.lua` in `src`, the line it pauses on is incorrect:
[example.zip](https://github.com/user-attachments/files/16549073/example.zip)

**Comment by sewbacca** [comment]
You will have to generate source map files, in order for LLD to match lines back to its original source. I don't know the details for that, but here a quote from the README:
> `scriptFiles`
> A list of glob patterns identifying where to find Lua scripts in the workspace when debugging. This is required for placing breakpoints in sourcemapped files (ex. 'ts' scripts when using TypescriptToLua), as the source files must be looked up ahead of time so that breakpoints can be resolved.

The README doesn't explicitly say that you need `.map` files, but when I fiddled arround with the debugger (which is written in TypeScript and compiled to Lua) I noticed it used `.map` files to map Lua lines back to TypeScript lines.

So you will need to create adjacent `.map` files. A short search yielded this [SO post about source maps](https://stackoverflow.com/questions/21719562/how-can-i-use-javascript-source-maps-map-files). I can't help you much with that, but since I am interested in this topic as well, I'd apreciate if you keep me posted about the progress you've made.

**Comment by SHiLLySiT** [comment]
Got it, thank you for your transparency! I also only had limited knowledge of source maps, so I had hoped maybe this debugger was doing something magic to generate them once started 😂 

Doing a brief deep dive on sourcemaps, it seems doable for my tech stack. The trouble is that I use an external tool to process the Lua files and it doesn't appear to support generating source maps, so I'll have to figure out how to add support to the tool.

I think this will be a good feature to support, so I added [a ticket](https://github.com/GamesRightMeow/playbit/issues/17) in my project to capture this work. I'll close this for now, and hopefully remember to circle back if I figure out how to get it working.
